-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ct_donhang
(
    id bigserial NOT NULL,
    donhang_id bigint NOT NULL,
    sanpham_id bigint NOT NULL,
    giatien character varying(255) COLLATE pg_catalog."default" NOT NULL,
    soluong character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tensanpham character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hinhanh character varying(255) COLLATE pg_catalog."default" NOT NULL,
    size character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tongtien double precision NOT NULL DEFAULT 0.00,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ct_donhang_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.donhang
(
    id bigserial NOT NULL,
    ten character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    diachi character varying(255) COLLATE pg_catalog."default",
    sodienthoai character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    trangthai character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT donhang_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.nguoidung
(
    id serial NOT NULL,
    tennguoidung character varying(255) COLLATE pg_catalog."default" NOT NULL,
    matkhau character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vaitro_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    description smallint NOT NULL DEFAULT 0,
    CONSTRAINT nguoidung_pkey PRIMARY KEY (id),
    CONSTRAINT nguoidung_email_key UNIQUE (email),
    CONSTRAINT nguoidung_tennguoidung_key UNIQUE (tennguoidung)
);

CREATE TABLE IF NOT EXISTS public.phanloai
(
    id serial NOT NULL,
    phanloai_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT phanloai_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sanpham
(
    id bigserial NOT NULL,
    phanloai_id integer,
    ten character varying(255) COLLATE pg_catalog."default",
    gia numeric(38, 2) NOT NULL DEFAULT 0.000,
    anh character varying(255) COLLATE pg_catalog."default",
    mota character varying(255) COLLATE pg_catalog."default",
    soluong integer,
    size character varying(255) COLLATE pg_catalog."default",
    masp character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sanpham_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vaitro
(
    id bigserial NOT NULL,
    tenvaitro character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT vaitro_pkey PRIMARY KEY (id),
    CONSTRAINT vaitro_tenvaitro_key UNIQUE (tenvaitro)
);

ALTER TABLE IF EXISTS public.ct_donhang
    ADD CONSTRAINT ct_donhang_donhang_id_fkey FOREIGN KEY (donhang_id)
    REFERENCES public.donhang (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ct_donhang
    ADD CONSTRAINT ct_donhang_sanpham_id_fkey FOREIGN KEY (sanpham_id)
    REFERENCES public.sanpham (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.nguoidung
    ADD CONSTRAINT nguoidung_vaitro_id_fkey FOREIGN KEY (vaitro_id)
    REFERENCES public.vaitro (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sanpham
    ADD CONSTRAINT sanpham_phanloai_id_fkey FOREIGN KEY (phanloai_id)
    REFERENCES public.phanloai (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;